"""Shared pytest fixtures for Rugix's pytest test suite."""

from __future__ import annotations

import logging
import sys
from collections.abc import Generator
from functools import partial
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path
from threading import Thread

import pytest

# This conftest lives at the bakery project root (next to ``rugix-bakery.toml``).
PROJECT_DIR = Path(__file__).resolve().parent
PRIVATE_KEY = PROJECT_DIR / "keys" / "id_rsa"

sys.path.insert(0, str(PROJECT_DIR))

from harness import BakeryBuilder, build_amd64_vm_config  # noqa: E402
from rugix_testkit import RugixCtrl, SystemInfo, VMHandle  # noqa: E402

logger = logging.getLogger(__name__)


def pytest_configure(config: pytest.Config) -> None:
    config.addinivalue_line("markers", "slow: long-running tests")


def pytest_addoption(parser: pytest.Parser) -> None:
    parser.addoption(
        "--test-outputs-dir",
        default="test-outputs",
        help="Directory for test artifacts (default: test-outputs/)",
    )


@pytest.hookimpl(wrapper=True)
def pytest_runtest_makereport(
    item: pytest.Item, call: pytest.CallInfo[None]
) -> Generator[None, pytest.TestReport, pytest.TestReport]:
    report = yield
    if report.when == "call":
        _dump_test_artifacts(item)
    return report


@pytest.fixture(scope="session")
def project_dir() -> Path:
    """The bakery project directory (where ``rugix-bakery.toml`` lives)."""
    if not (PROJECT_DIR / "rugix-bakery.toml").is_file():
        pytest.fail(f"rugix-bakery.toml not found at {PROJECT_DIR}")
    return PROJECT_DIR


@pytest.fixture(scope="session")
def private_key(project_dir: Path) -> Path:
    """SSH private key generated by ``generate-test-keys.sh``."""
    if not PRIVATE_KEY.is_file():
        pytest.fail(
            f"SSH key not found: {PRIVATE_KEY}. Run ./generate-test-keys.sh first."
        )
    return PRIVATE_KEY


@pytest.fixture(scope="session")
def bakery(project_dir: Path) -> BakeryBuilder:
    return BakeryBuilder(project_dir)


@pytest.fixture(scope="session")
def http_server(project_dir: Path) -> Generator[HTTPServer]:
    """Serve the bakery's ``build/`` directory over HTTP for bundle downloads."""
    handler = partial(_QuietHandler, directory=str(project_dir / "build"))
    server = HTTPServer(("0.0.0.0", 0), handler)
    Thread(target=server.serve_forever, daemon=True).start()
    logger.info("HTTP server on port %d", server.server_port)
    yield server
    server.shutdown()


@pytest.fixture
def boot_system() -> str:
    """Bakery system to boot for the test. Override at module scope.

    Defaults to ``customized-amd64`` because most tests boot it; override
    via a module-level ``boot_system`` fixture (or pytest parametrization)
    when a test needs a different image.
    """
    return "customized-amd64"


@pytest.fixture
def boot_timeout() -> float:
    """SSH boot timeout in seconds. Override for slow-booting images."""
    return 300.0


@pytest.fixture
def amd64_vm(
    bakery: BakeryBuilder,
    private_key: Path,
    boot_system: str,
    boot_timeout: float,
    request: pytest.FixtureRequest,
) -> Generator[VMHandle]:
    """Boot the configured ``boot_system`` and tear it down after the test."""
    image = bakery.bake_image(boot_system)
    config = build_amd64_vm_config(image)
    with VMHandle.start(
        config, private_key=private_key, boot_timeout=boot_timeout
    ) as handle:
        request.node._vm_handle = handle
        yield handle


@pytest.fixture
def rugix(amd64_vm: VMHandle) -> RugixCtrl:
    return RugixCtrl(amd64_vm)


def assert_boot(rugix: RugixCtrl, *, default: str, active: str) -> SystemInfo:
    """Read system info and assert ``default_group`` / ``active_group``."""
    info = rugix.system_info()
    assert info.default_group == default, (
        f"defaultGroup: expected {default!r}, got {info.default_group!r}"
    )
    assert info.active_group == active, (
        f"activeGroup: expected {active!r}, got {info.active_group!r}"
    )
    return info


def install_and_reboot(
    rugix: RugixCtrl,
    bundle: Path,
    *,
    verify: bool = False,
    root_cert: str | None = None,
) -> None:
    """Upload *bundle*, install with ``--reboot yes``, and reconnect SSH.

    rugix-ctrl triggers the reboot itself, which closes the SSH connection
    mid-command — the swallowed exception is expected. Pass ``verify=True``
    for signed bundles where bundle verification should run.
    """
    try:
        rugix.update_install_file(
            bundle,
            reboot="yes",
            insecure=not verify,
            root_cert=root_cert,
            check=False,
            timeout=600,
        )
    except Exception:
        pass
    rugix.vm.wait_for_reboot()


def _dump_test_artifacts(item: pytest.Item) -> None:
    handle: VMHandle | None = getattr(item, "_vm_handle", None)
    if handle is None:
        return

    outputs_dir = Path(item.config.getoption("--test-outputs-dir"))
    safe_name = item.nodeid.replace("::", "--").replace("/", "--")
    artifact_dir = outputs_dir / safe_name
    artifact_dir.mkdir(parents=True, exist_ok=True)

    serial = handle.serial_output
    if serial:
        (artifact_dir / "serial.log").write_text(serial)

    history = handle.command_history
    if history:
        (artifact_dir / "commands.log").write_text(
            "\n\n".join(str(cmd) for cmd in history) + "\n"
        )


class _QuietHandler(SimpleHTTPRequestHandler):
    def log_message(self, format: str, *args: object) -> None:
        logger.debug("http: " + format, *args)
