"""Shared pytest fixtures for Rugix's pytest test suite."""

from __future__ import annotations

import logging
import os
import sys
from collections.abc import Callable, Generator
from functools import partial
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path
from threading import Thread

import pytest

EXTENDED_ENV = "RUGIX_TESTS_EXTENDED"

# This conftest lives at the bakery project root (next to ``rugix-bakery.toml``).
PROJECT_DIR = Path(__file__).resolve().parent
PRIVATE_KEY = PROJECT_DIR / "keys" / "id_rsa"

sys.path.insert(0, str(PROJECT_DIR))

from harness import BakeryBuilder, build_amd64_vm_config  # noqa: E402
from rugix_testkit import RugixCtrl, SystemInfo, VMHandle  # noqa: E402

logger = logging.getLogger(__name__)


def pytest_configure(config: pytest.Config) -> None:
    config.addinivalue_line("markers", "slow: long-running tests")
    config.addinivalue_line(
        "markers",
        f"extended: tests outside the default suite (run with {EXTENDED_ENV}=1)",
    )


def pytest_collection_modifyitems(
    config: pytest.Config, items: list[pytest.Item]
) -> None:
    """Skip ``@pytest.mark.extended`` tests unless ``$RUGIX_TESTS_EXTENDED`` is set."""
    if os.environ.get(EXTENDED_ENV):
        return
    skip = pytest.mark.skip(reason=f"set {EXTENDED_ENV}=1 to enable")
    for item in items:
        if "extended" in item.keywords:
            item.add_marker(skip)


def pytest_addoption(parser: pytest.Parser) -> None:
    parser.addoption(
        "--test-outputs-dir",
        default="test-outputs",
        help="Directory for test artifacts (default: test-outputs/)",
    )


@pytest.hookimpl(wrapper=True)
def pytest_runtest_makereport(
    item: pytest.Item, call: pytest.CallInfo[None]
) -> Generator[None, pytest.TestReport, pytest.TestReport]:
    report = yield
    if report.when == "call":
        _dump_test_artifacts(item)
    return report


@pytest.fixture(scope="session")
def project_dir() -> Path:
    """The bakery project directory (where ``rugix-bakery.toml`` lives)."""
    if not (PROJECT_DIR / "rugix-bakery.toml").is_file():
        pytest.fail(f"rugix-bakery.toml not found at {PROJECT_DIR}")
    return PROJECT_DIR


@pytest.fixture(scope="session")
def private_key(project_dir: Path) -> Path:
    """SSH private key generated by ``generate-test-keys.sh``."""
    if not PRIVATE_KEY.is_file():
        pytest.fail(
            f"SSH key not found: {PRIVATE_KEY}. Run ./generate-test-keys.sh first."
        )
    return PRIVATE_KEY


@pytest.fixture(scope="session")
def bakery(project_dir: Path) -> BakeryBuilder:
    return BakeryBuilder(project_dir)


@pytest.fixture(scope="session")
def http_server(project_dir: Path) -> Generator[HTTPServer]:
    """Serve the project root over HTTP so VMs can fetch baked artifacts.

    The QEMU user-mode network gateway (``10.0.2.2``) routes back to the
    host, so ``http://10.0.2.2:<port>/<rel>`` from inside the VM hits this
    server's static file tree.
    """
    handler = partial(_QuietHandler, directory=str(project_dir))
    server = HTTPServer(("0.0.0.0", 0), handler)
    Thread(target=server.serve_forever, daemon=True).start()
    logger.info("HTTP server on port %d", server.server_port)
    yield server
    server.shutdown()


@pytest.fixture
def bundle_url(http_server: HTTPServer) -> Callable[[Path], str]:
    """Return a function that converts a path under the project to a VM-side URL."""
    base = f"http://10.0.2.2:{http_server.server_port}"

    def _url(path: Path) -> str:
        rel = path.resolve().relative_to(PROJECT_DIR)
        return f"{base}/{rel}"

    return _url


@pytest.fixture
def boot_system() -> str:
    """Bakery system to boot for the test. Override at module scope.

    Defaults to ``customized-amd64`` because most tests boot it; override
    via a module-level ``boot_system`` fixture (or pytest parametrization)
    when a test needs a different image.
    """
    return "customized-amd64"


@pytest.fixture
def boot_timeout() -> float:
    """SSH boot timeout in seconds. Override for slow-booting images."""
    return 300.0


@pytest.fixture
def amd64_vm(
    bakery: BakeryBuilder,
    private_key: Path,
    boot_system: str,
    boot_timeout: float,
    request: pytest.FixtureRequest,
) -> Generator[VMHandle]:
    """Boot the configured ``boot_system`` and tear it down after the test."""
    image = bakery.bake_image(boot_system)
    config = build_amd64_vm_config(image)
    with VMHandle.start(
        config, private_key=private_key, boot_timeout=boot_timeout
    ) as handle:
        request.node._vm_handle = handle
        yield handle


@pytest.fixture
def rugix(amd64_vm: VMHandle) -> RugixCtrl:
    return RugixCtrl(amd64_vm)


def assert_boot(rugix: RugixCtrl, *, default: str, active: str) -> SystemInfo:
    """Read system info and assert ``default_group`` / ``active_group``."""
    info = rugix.system_info()
    assert info.default_group == default, (
        f"defaultGroup: expected {default!r}, got {info.default_group!r}"
    )
    assert info.active_group == active, (
        f"activeGroup: expected {active!r}, got {info.active_group!r}"
    )
    return info


def install_and_reboot(
    rugix: RugixCtrl,
    source: str,
    *,
    verify: bool = False,
    root_cert: str | None = None,
) -> None:
    """Install from *source*, reboot, and reconnect SSH.

    *source* is forwarded verbatim to ``rugix-ctrl update install`` —
    typically a URL produced by the :func:`bundle_url` fixture, but a
    path on the VM also works. Use ``verify=True`` for signed bundles.

    ``rugix-ctrl --reboot yes`` triggers the reboot itself and the SSH
    connection drops mid-command; the swallowed exception is expected.
    """
    try:
        rugix.update_install(
            source,
            reboot="yes",
            insecure=not verify,
            root_cert=root_cert,
            check=False,
            timeout=600,
        )
    except Exception:
        pass
    rugix.vm.wait_for_reboot()


def _dump_test_artifacts(item: pytest.Item) -> None:
    handle: VMHandle | None = getattr(item, "_vm_handle", None)
    if handle is None:
        return

    outputs_dir = Path(item.config.getoption("--test-outputs-dir"))
    safe_name = item.nodeid.replace("::", "--").replace("/", "--")
    artifact_dir = outputs_dir / safe_name
    artifact_dir.mkdir(parents=True, exist_ok=True)

    serial = handle.serial_output
    if serial:
        (artifact_dir / "serial.log").write_text(serial)

    history = handle.command_history
    if history:
        (artifact_dir / "commands.log").write_text(
            "\n\n".join(str(cmd) for cmd in history) + "\n"
        )


class _QuietHandler(SimpleHTTPRequestHandler):
    def log_message(self, format: str, *args: object) -> None:
        logger.debug("http: " + format, *args)
