[repositories]
rugix-extra = { git = "https://github.com/rugix/rugix-extra.git" }

[systems.tryboot]
layer = "customized"
architecture = "arm64"
target = "rpi-tryboot"

[systems.tryboot-pi4]
layer = "customized-pi4"
architecture = "arm64"
target = "rpi-tryboot"

[systems.u-boot]
layer = "customized"
architecture = "arm64"
target = "rpi-uboot"

[systems.u-boot-armhf]
layer = "customized"
architecture = "armhf"
target = "rpi-uboot"

[systems.customized-amd64]
layer = "customized-efi"
architecture = "amd64"
target = "generic-grub-efi"

# This image has a larger size and can be directly used with QEMU.
[systems.customized-amd64-vm]
layer = "customized-efi"
architecture = "amd64"
target = "generic-grub-efi"
size = "16G"

[systems.customized-amd64-delta]
layer = "customized-efi-delta"
architecture = "amd64"
target = "generic-grub-efi"

[systems.customized-amd64-squashfs]
layer = "customized-efi"
architecture = "amd64"
target = "generic-grub-efi"
options = { use-squashfs = { no-compression = true } }

[systems.customized-amd64-delta-squashfs]
layer = "customized-efi-delta"
architecture = "amd64"
target = "generic-grub-efi"
options = { use-squashfs = { no-compression = true } }

[systems.customized-slots]
layer = "customized-slots"
architecture = "amd64"
target = "generic-grub-efi"

[systems.customized-temp-overlay]
layer = "customized-temp-overlay"
architecture = "amd64"
target = "generic-grub-efi"

[systems.customized-amd64-docker]
layer = "customized-efi-docker"
architecture = "amd64"
target = "generic-grub-efi"

[systems.customized-amd64-deb-musl]
layer = "customized-efi-deb"
architecture = "amd64"
target = "generic-grub-efi"

[systems.customized-amd64-deb-gnu]
layer = "customized-efi-deb-gnu"
architecture = "amd64"
target = "generic-grub-efi"

[systems.old-debian-snapshot]
layer = "old-debian-snapshot"
architecture = "amd64"
target = "generic-grub-efi"
