parent = "core/debian-trixie"

recipes = [
    "core/debian-grub-setup",
    "break-init-config",
    "append-grub-kernel-args",
]

[parameters."core/rugix-ctrl"]
version = "container"

[parameters.append-grub-kernel-args]
args = "console=ttyS0 rugix.init.shell_on_error=10"
