"""Port of ``tests/tests/test-update-bundle-signed.toml``.

Boots ``customized-amd64``, configures /etc/rugix/ctrl.toml with the test
root cert, then verifies that a signed bundle is rejected when the wrong
root cert is provided and accepted with the correct one. The signed bundle
is produced by ``bundler signatures sign`` against ``keys/signer.{crt,key}``
generated by ``tests/generate-test-keys.sh``.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from conftest import assert_boot, install_and_reboot
from harness import BakeryBuilder
from rugix_testkit import CmdError, RugixCtrl, VMHandle

CTRL_CONFIG = """\
[signatures]
roots = ["/etc/rugix/root.crt"]
"""


@pytest.fixture(scope="session")
def signed_bundle(bakery: BakeryBuilder, project_dir: Path) -> Path:
    """Build a signed bundle: bake then sign with keys/signer.{crt,key}."""
    base = bakery.bake_bundle("customized-amd64")
    output = project_dir / "build" / "customized-amd64-signed.rugixb"
    if not output.exists():
        bakery.bundler_sign(
            base,
            project_dir / "keys" / "signer.crt",
            project_dir / "keys" / "signer.key",
            output,
        )
    return output


@pytest.mark.slow
def test_update_bundle_signed(
    amd64_vm: VMHandle,
    rugix: RugixCtrl,
    signed_bundle: Path,
) -> None:
    amd64_vm.run(
        ["sh", "-c", f"cat > /etc/rugix/ctrl.toml <<'TOML'\n{CTRL_CONFIG}TOML"],
        hide=True,
    )
    assert_boot(rugix, default="a", active="a")

    # Wrong root certificate must be rejected.
    with pytest.raises(CmdError):
        rugix.update_install_file(
            signed_bundle,
            insecure=False,
            root_cert="/etc/rugix/other-root.crt",
            timeout=300,
        )

    install_and_reboot(rugix, signed_bundle, verify=True)

    assert_boot(rugix, default="a", active="b")
    rugix.system_commit()
    assert_boot(rugix, default="b", active="b")
